//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSloon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public string ModelName { get; set; }
        public string Coast { get; set; }
        public int Count { get; set; }
        public string Location { get; set; }
        public string MaxSpeed { get; set; }
        public string Box { get; set; }
        public string Rashod { get; set; }
        public string Razgin { get; set; }
        public string Engine { get; set; }
        public string Privod { get; set; }
    }
}
